#! /bin/sh

bspc monitor DisplayPort-0 -d I II III IV V
bspc monitor HDMI-A-0 -d VI VII VIII IX X
pgrep -x sxhkd > /dev/null || sxhkd -m -1 &
flameshot &
dunst &
nm-applet &
picom &
xfce4-power-manager &
$HOME/.config/polybar/launch.sh &
feh --bg-fill ~/Pictures/wallpaper/wallpaper_2big.png ~/Pictures/wallpaper/wallpaper_1.png &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Config
bspc config ignore_ewmh_struts true
bspc config border_width         4
bspc config window_gap           3
bspc config top_padding          44
bspc config normal_border_color "#000000"
bspc config focused_border_color "#00085e"
bspc config normal_urgent_color "#ff0000"
# bspc config focus_follows_pointer     true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a "osu!" desktop=^8
bspc rule -a KeyOverlay desktop=^8 state=floating
# bspc rule -a discord desktop=^3
# bspc rule -a firefox desktop=^2
# bspc rule -a kitty desktop=^7
