#! /bin/sh

bspc monitor DisplayPort-0 -d 1 kitty game 4 music
bspc monitor HDMI-A-0 -d 6 firefox discord 9 10
pgrep -x sxhkd > /dev/null || sxhkd &
unclutter &
flameshot &
dunst &
# picom -b --experimental-backends
$HOME/.config/polybar/launch.sh
feh --bg-fill ~/Pictures/wallpaper/primary.jpg ~/Pictures/wallpaper/1920x1080.jpg
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Config

bspc config ignore_ewmh_struts true
bspc config border_width         2
bspc config window_gap           0
bspc config top_padding          40
bspc config normal_border_color "#000000"
bspc config focused_border_color "#00085e"
bspc config normal_urgent_color "#ff0000"
# bspc config focus_follows_pointer	true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules

bspc rule -a osu!.exe desktop=^8
bspc rule -a KeyOverlay desktop=^8
# bspc rule -a discord desktop=^3
# bspc rule -a firefox desktop=^2
# bspc rule -a kitty desktop=^7

# Extra


xsetroot -cursor_name left_ptr &
setxkbmap -model pc104 -layout se &
