#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#xrdb ~/.Xresources
export OSU_SONG_FOLDER=/media/mass/bald/songs
export QT_QPA_PLATFORMTHEME=qt5ct
xsetroot -cursor_name left_ptr &
setxkbmap -model pc104 -layout se &
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 74.99 --pos 0x180 --output DisplayPort-0 --mode 2560x1440 --primary --rate 144 --pos 1920x0 &
numlockx &
exec bspwm
